name: Periodic health check

on:
  schedule:
    # At 00:00.
    - cron: '0 0 * * *'

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://full-stack-cicd-pokedex-app.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s